googleapis/langchain-google-cloud-sql-pg-python

- integration.cloudbuild.yaml
- pyproject.toml
- src/langchain_google_cloud_sql_pg/__init__.py
- src/langchain_google_cloud_sql_pg/postgresql_engine.py
- tests/test_postgresql_engine.py
> feat: add PostgreSQLEngine

- docs/chat_message_history.ipynb
- docs/document_loader.ipynb
- docs/vector_store.ipynb
Langchain documentation seems to be strict on requiring an additional blank `\n` line before ordered or unordered lists begin.
Current [langchain docs](https://python.langchain.com/docs/integrations/document_loaders/google_cloud_sql_pg#cloud-sql-engine):
Proper docs:
> chore: fix rendering in LangChain docs

- README.md
PostgresEngine.from_instance() is missing project ID in README, adding it.
> chore: update README usages

- .github/header-checker-lint.yml
- .github/sync-repo-settings.yaml
- DEVELOPER.md
- integration.cloudbuild.yaml
- pyproject.toml
- requirements-3.8.txt
- tests/test_cloudsql_vectorstore_index.py
> feat(ci): test against multiple versions

- src/langchain_google_cloud_sql_pg/vectorstore.py
- tests/test_cloudsql_vectorstore.py
- tests/test_cloudsql_vectorstore_from_methods.py
Found a typo in docstring, referring to an old POC naming pattern.
> chore: update typos

- src/langchain_google_cloud_sql_pg/vectorstore.py
- tests/test_cloudsql_vectorstore.py
Adding basic test for vector store `.delete` method.
Update: failing test for custom table name discovered that special characters in table name were unable to delete from the vector store.
> fix: allow special characters in table name for vector store delete 

- pyproject.toml
- requirements.txt
This library uses only async SQLAlchemy connection pool engines. Thus, it should be depending on sqlalchemy[asyncio] and not just sqlalchemy.
This will fix required deps on macOS: https://docs.sqlalchemy.org/en/20/orm/extensions/asyncio.html#asyncio-platform-installation-notes-including-apple-m1
Port of https://github.com/googleapis/langchain-google-alloydb-pg-python/pull/116
> fix: update required dep to SQLAlchemy[asyncio]

- src/langchain_google_cloud_sql_pg/engine.py
We should be returning early and skipping the overhead of the API call if we already know the IAM principal based on the credentials attribute. This is what we do already in the [Cloud SQL MySQL package](https://github.com/googleapis/langchain-google-cloud-sql-mysql-python/blob/main/src/langchain_google_cloud_sql_mysql/engine.py#L73).
Port of https://github.com/googleapis/langchain-google-alloydb-pg-python/pull/117
> refactor: return early if credentials have service account field

- src/langchain_google_cloud_sql_pg/vectorstore.py
- tests/test_cloudsql_vectorstore.py
All table names should be wrapped in quotes to support special characters like dashes
> fix: missing quote in table name

- src/langchain_google_cloud_sql_pg/engine.py
- tests/test_postgresql_engine.py
- tests/test_postgresql_loader.py
> feat: add support for quota project

- pyproject.toml
- src/langchain_google_cloud_sql_pg/engine.py
The Cloud SQL Python Connector just released a new version `v1.10.0`
that supports setting the `refresh_strategy` argument of the connector.
Setting the refresh strategy to lazy refresh is recommended for
serverless environments. As the default refresh strategy is to
have background refreshes occur to get the instance metadata and a fresh
certificate to use for the SSL/TLS connection.
However, these background refreshes can be throttled when serverless
environments scale to zero (Cloud Functions, Cloud Run etc.).
This PR will fix the ambiguous errors that are a result of the CPU being
throttled for the Cloud SQL Connector.
> fix: use lazy refresh for Cloud SQL Connector

- src/langchain_google_cloud_sql_pg/indexes.py
`pgvector` has IVFFlat lists parameter default to 100(https://github.com/pgvector/pgvector/blob/d1694a93afe4d23d0bc3ca6f9c85f06fb79a325c/src/ivfflat.h#L42) but our implementation defaults to 1. We should change the default to match the `pgvector` setting.
> fix: Change IVFFlat `lists` default to 100

- src/langchain_google_cloud_sql_pg/engine.py
- tests/test_postgresql_engine.py
Add key object to engine constructor to prevent constructor usage.
> feat: Add `key` to engine constructor

- src/langchain_google_cloud_sql_pg/loader.py
- src/langchain_google_cloud_sql_pg/vectorstore.py
- tests/test_cloudsql_vectorstore.py
If the user doesn't provide IDs when adding vector store embeddings, auto-generate integer IDs for them.
> feat: Auto-generate IDs upon adding embeddings

- .coveragerc
- src/langchain_google_cloud_sql_pg/vectorstore.py
- tests/test_cloudsql_vectorstore_search.py
Implements LangChain `_select_relevance_score_fn` function to support similarity search with score threshold: https://github.com/langchain-ai/langchain/blob/cb95198398a66737f1a7f7e0f63417802e03190c/libs/core/langchain_core/vectorstores/base.py#L611
> feat: Add similarity search score threshold select function

- src/langchain_google_cloud_sql_pg/indexes.py
- src/langchain_google_cloud_sql_pg/vectorstore.py
- tests/test_cloudsql_vectorstore_index.py
Add table name as prefix to default index name upon index creation to avoid conflicting default index names for different tables.
1. Change `DEFAULT_INDEX_NAME` to `DEFAULT_INDEX_NAME_SUFFIX`.
2. Change `index_name` default in the `BaseIndex` class to `None`.
3. In `aapply_vector_index()`, check if the index_name field is `None` and if so, give it a default index name (table_name + DEFAULT_INDEX_NAME_SUFFIX).
> feat: Add table name to default index name

- pyproject.toml
- requirements.txt
- samples/requirements.txt
- src/langchain_google_cloud_sql_pg/loader.py
- tests/test_cloudsql_vectorstore.py
- tests/test_cloudsql_vectorstore_from_methods.py
- tests/test_cloudsql_vectorstore_index.py
- tests/test_cloudsql_vectorstore_search.py
- tests/test_postgresql_engine.py
We choose langchain-core as the langchain library to use for this repo. This PR removes denpendency on langchain-community and replaces APIs with corresponding ones from langchain-core.
> feat: Remove langchain-community dependency

- src/langchain_google_cloud_sql_pg/engine.py
- src/langchain_google_cloud_sql_pg/vectorstore.py
The index QueryOptions are set by executing SET LOCAL, whose effect only last within the same transaction. However, currently the similarity search is in a different transaction, which means the query options are never applied. I fixed this by creating a new _afetch_with_query_options(query, query_options) method that executes the query options statement before fetching similarity search result, and modify the search APIs to call this method instead of _afetch()
> fix: Fix QueryOptions not applied to similarity search bug

- integration.cloudbuild.yaml
Currently integration tests leverage the Cloud SQL Proxy v1 to
test `from_engine()`:
https://github.com/googleapis/langchain-google-cloud-sql-pg-python/blob/42baac64c9c5edba9e2ed53c983155579805fd5b/integration.cloudbuild.yaml#L32-L33
It is recommended to use the Cloud SQL Proxy v2 ([v2.13.0](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/releases/tag/v2.13.0) as of writing)
as it is more feature rich, stable, and has a better CLI interface.
This PR swaps out the v1 Cloud SQL Proxy for the v2 version as outlined
in the [migration guide](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/main/migration-guide.md#migrating-from-v1-to-v2).
> ci: use Cloud SQL Proxy v2 for tests

- src/langchain_google_cloud_sql_pg/async_vectorstore.py
- src/langchain_google_cloud_sql_pg/engine.py
- src/langchain_google_cloud_sql_pg/vectorstore.py
- tests/test_async_vectorstore_from_methods.py
- tests/test_engine.py
- tests/test_vectorstore_from_methods.py
feat: allow non-uuid data types for vectorstore primary key
> feat: allow non-uuid data types for vectorstore primary key

- .github/sync-repo-settings.yaml
- DEVELOPER.md
- README.rst
- integration.cloudbuild.yaml
- pyproject.toml
- requirements.txt
Langchain v0.3 remove support for py3.8. Py3.8 within the year will be EOL; therefore removing support from future versions.
> feat: remove support for Python 3.8

- samples/index_tuning_sample/README.md
- samples/langchain_on_vertexai/prebuilt_langchain_agent_template.py
- src/langchain_google_cloud_sql_pg/async_chat_message_history.py
- src/langchain_google_cloud_sql_pg/async_loader.py
- src/langchain_google_cloud_sql_pg/async_vectorstore.py
- src/langchain_google_cloud_sql_pg/chat_message_history.py
- src/langchain_google_cloud_sql_pg/engine.py
- src/langchain_google_cloud_sql_pg/indexes.py
- src/langchain_google_cloud_sql_pg/loader.py
- src/langchain_google_cloud_sql_pg/vectorstore.py
- tests/test_async_chatmessagehistory.py
- tests/test_chatmessagehistory.py
As of Python 3.9 and [PEP 585](https://peps.python.org/pep-0585/#implementation) we can use standard collections like
`list`, `dict`, `tuple` for typing instead of the  now deprecated
```python
from typing import Dict, List, Tuple ...
```
Also removing a ton of unused imports.
> chore: adhere to PEP 585 and removed unused imports

- src/langchain_google_cloud_sql_pg/engine.py
- tests/test_engine.py
> feat: add engine_args argument to engine creation functions

- tests/test_async_vectorstore_index.py
- tests/test_vectorstore_index.py
Adding delete index statements to avoid `DuplicateTableError: Index already exists` errors.
Adding these as part of auditing the other repos across LC & LI, for alloy db & Cloud sql
> chore: add drop index statements to avoid conflict

- src/langchain_google_cloud_sql_pg/async_vectorstore.py
chore: Enquote column names to not match reserved keywords.
> fix: Enquote column names to not match reserved keywords.

- pyproject.toml
- src/langchain_google_cloud_sql_pg/engine.py
- tests/test_engine.py
> feat: add engine methods

- docs/chat_message_history.ipynb
- docs/document_loader.ipynb
- docs/vector_store.ipynb
- samples/langchain_quick_start.ipynb
chore(docs): Highlight how to use Private IP in Engine class.
> chore(docs): Highlight how to use Private IP in Engine class.

- pyproject.toml
- tests/test_standard_test_suite.py
Adding Langchain standard test suite for vectorstore for edge cases.
Fixes [b/375659546](https://b.corp.google.com/issues/375659546)
> chore: Add Langchain vectorstore standard suite tests

- src/langchain_google_cloud_sql_pg/async_vectorstore.py
- src/langchain_google_cloud_sql_pg/vectorstore.py
- tests/test_async_vectorstore_search.py
- tests/test_vectorstore_search.py
feat: Add get_by_ids and aget_by_ids to vectorstore
> feat: Add get_by_ids and aget_by_ids to vectorstore

- src/langchain_google_cloud_sql_pg/async_vectorstore.py
- tests/test_engine.py
Per [this comment](https://github.com/googleapis/langchain-google-cloud-sql-pg-python/pull/251#issuecomment-2685689377), separating out the code changes for numpy #V2.
This change is needed because when using numpy V2, if a numpy array is converted to string then it comes as numpy objects rather than float array. [ref](https://github.com/googleapis/langchain-google-cloud-sql-pg-python/issues/247#issuecomment-2652914015)
1. Parsing embedding dimensions individually for accommodating numpy V2 values.
2. Updating tests accordingly.
> refactor: parse embedding dimensions as float[] for numpyV2

- requirements.txt
- src/langchain_google_cloud_sql_pg/async_checkpoint.py
- src/langchain_google_cloud_sql_pg/engine.py
- tests/test_async_checkpoint.py
- tests/test_engine.py
> feat: add checkpoint aput method and test

- pyproject.toml
- src/langchain_google_cloud_sql_pg/async_checkpoint.py
- src/langchain_google_cloud_sql_pg/engine.py
- tests/test_async_checkpoint.py
- tests/test_engine.py
> feat: add checkpoint aget tuple method

- src/langchain_google_cloud_sql_pg/async_checkpoint.py
- src/langchain_google_cloud_sql_pg/checkpoint.py
- tests/test_async_checkpoint.py
- tests/test_checkpoint.py
> feat: add checkpoint class

- README.rst
- docs/checkpointer.ipynb
- docs/langgraph_checkpoint.ipynb
> docs: update readme with setup instructions

- src/langchain_google_cloud_sql_pg/async_vectorstore.py
- src/langchain_google_cloud_sql_pg/vectorstore.py
- tests/metadata_filtering_data.py
- tests/test_async_vectorstore_search.py
- tests/test_vectorstore_search.py
feat: Enable DB-Agnostic metadata filtering in vectorstores
> feat: Enable DB-Agnostic metadata filtering in vectorstores

- pyproject.toml
- src/langchain_google_cloud_sql_pg/async_vectorstore.py
- src/langchain_google_cloud_sql_pg/vectorstore.py
- tests/metadata_filtering_data.py
- tests/test_async_vectorstore_search.py
- tests/test_standard_test_suite.py
- tests/test_vectorstore_search.py
This PR updates the Postgres VectorStore to the updated expectations from LangChain.
The changes are:
- Documents added or retrieved from the vectorstore can now support the ID property
- Support for de-duplication of ID by implementing upsert to add documents
- Enabled support for DB Agnostic filtering (metadata filtering)
- The (a)get_by_ids function is now supported
- The LangChain standard suite testing is now enabled
> feat: Update Postgres VectorStore to expected LangChain functionality

- README.rst
chore(docs): Update readme on how to convert sync to async
Fixes #245  🦕
> chore(docs): Update readme on how to convert sync to async

- tests/test_async_checkpoint.py
- tests/test_checkpoint.py
Lint seems to be failing for checkpointer tests, [ref test log](https://github.com/googleapis/langchain-google-cloud-sql-pg-python/actions/runs/14626509139/job/41039195997?pr=297) in another PR: https://github.com/googleapis/langchain-google-cloud-sql-pg-python/pull/297
> chore(lint): fix lint in checkpointer tests

- requirements.txt
- src/langchain_google_cloud_sql_pg/engine.py
- tests/test_async_checkpoint.py
- tests/test_checkpoint.py
The new version of connectors for Alloy DB are leading to test failures, ref tests in https://github.com/googleapis/langchain-google-cloud-sql-pg-python/pull/297.
This PR pins the issue to connector's latest version so that other packages can be unblocked from version updates.
1. In the first commit of PR, the session dispose is NOT commented out. This leads to failures like `RuntimeError: Session is closed` in several tests during test run. [Ref GCB log](https://pantheon.corp.google.com/cloud-build/builds/9d0c8618-9291-4af5-a4c6-f022b105f5d8;step=3?e=13802955&mods=logs_tg_staging&project=langchain-cloud-sql-testing)
2. In the second iteration of this PR, the session dispose is commented out ensuring sessions are not disposed/closed at all. This leads to `RuntimeError: Session is closed` …
> chore(deps): update connectors

- src/langchain_google_cloud_sql_pg/async_vectorstore.py
- tests/test_async_vectorstore.py
fix: Add support for a metadata column named id
Fixes an issue that prevented adding a metadata column named id to the vector store, due to a conflict with the id parameter in the insert query. Users can now successfully include a metadata field with the name id.
Following the same fix as https://github.com/googleapis/langchain-google-alloydb-pg-python/pull/421
> fix: Add support for a metadata column named id
