googleapis/langchain-google-cloud-sql-pg-python

- src/langchain_google_cloud_sql_pg/cloudsql_vectorstore.py
- tests/test_cloudsql_vectorstore.py
- tests/test_cloudsql_vectorstore_from_methods.py
- tests/test_postgresql_engine.py
Instead of https://github.com/googleapis/langchain-google-cloud-sql-pg-python/pull/15
> feat: add from methods

- src/langchain_google_cloud_sql_pg/cloudsql_vectorstore.py
- src/langchain_google_cloud_sql_pg/indexes.py
- tests/test_cloudsql_vectorstore.py
- tests/test_cloudsql_vectorstore_from_methods.py
- tests/test_cloudsql_vectorstore_search.py
Instead of https://github.com/googleapis/langchain-google-cloud-sql-pg-python/pull/16
> feat: add search methods

- .github/workflows/lint.yml
- .gitignore
- integration.cloudbuild.yaml
- pyproject.toml
- requirements.txt
Add a requirements.txt which will pin the required dependency versions we are using for tests. This will help us catch things that might change when we bump this version.
> chore(ci): add requirements.txt

- src/langchain_google_cloud_sql_pg/__init__.py
- src/langchain_google_cloud_sql_pg/postgresql_chat_message_history.py
- src/langchain_google_cloud_sql_pg/postgresql_engine.py
- tests/test_postgresql_chatmessagehistory.py
Changes Done
- Added the PostgreSQLChatMessageHistory 
- Added add_message, clear methods
- Added messages property
- Integration Tests added
Code cleanup
- Testing async methods pending
- Add additional Integration Tests to support added async methods
> CloudSQL Postgresql chatmessagehistory with Integration Tests

- src/langchain_google_cloud_sql_pg/cloudsql_vectorstore.py
- src/langchain_google_cloud_sql_pg/postgresql_engine.py
- tests/test_cloudsql_vectorstore.py
- tests/test_postgresql_chatmessagehistory.py
- tests/test_postgresql_engine.py
>  fix: update insert statement

- pyproject.toml
- src/langchain_google_cloud_sql_pg/__init__.py
- src/langchain_google_cloud_sql_pg/version.py
> chore(ci): standardize version format

- pyproject.toml
- src/langchain_google_cloud_sql_pg/engine.py
- src/langchain_google_cloud_sql_pg/version.py
> feat: add user_agent to client

- docs/chat_message_history.ipynb
Adding chatmessagehistory docs for cloudSQL
> docs: add chatmessagehistory docs

- docs/document_loader.ipynb
- src/langchain_google_cloud_sql_pg/__init__.py
- src/langchain_google_cloud_sql_pg/engine.py
- src/langchain_google_cloud_sql_pg/postgresql_loader.py
- tests/test_postgresql_loader.py
- Add PostgreSQL Loader and Saver
- Add init_document_table to PostgreSQL Engine class
- Integration Tests
- Documentation
> feat: Add PostgreSQL loader

- pyproject.toml
- src/langchain_google_cloud_sql_pg/vectorstore.py
> chore: remove dep on langchain-community

- pyproject.toml
- src/langchain_google_cloud_sql_pg/vectorstore.py
- tests/test_postgresql_loader.py
> fix(tests): remove duplicate function

- pyproject.toml
> chore(deps): fix lc-community dep

- docs/vector_store.ipynb
- src/langchain_google_cloud_sql_pg/engine.py
- tests/test_cloudsql_vectorstore.py
- tests/test_cloudsql_vectorstore_from_methods.py
- tests/test_cloudsql_vectorstore_index.py
- tests/test_cloudsql_vectorstore_search.py
- tests/test_postgresql_chatmessagehistory.py
- tests/test_postgresql_engine.py
> feat: add sync methods

- docs/document_loader.ipynb
- src/langchain_google_cloud_sql_pg/postgresql_loader.py
- tests/test_postgresql_loader.py
> feat: add create methods for Loader

- samples/langchain_quick_start.ipynb
> docs: Update langchain_quick_start.ipynb

- src/langchain_google_cloud_sql_pg/engine.py
- tests/test_postgresql_engine.py
> feat(engine): add from_engine method

- samples/langchain_quick_start.ipynb
> doc: fixing code lab

- samples/langchain_quick_start.ipynb
> doc: add back IAM user grant

- samples/langchain_quick_start.ipynb
> doc: fixing typo in codelab

- samples/langchain_quick_start.ipynb
Making small tweaks to quickstart notebook to make "Run all" work a bit more smooth and to link to Langchain and Cloud SQL docs.
> chore: update quickstart notebook

- README.md
- docs/chat_message_history.ipynb
- docs/document_loader.ipynb
- docs/vector_store.ipynb
- samples/langchain_quick_start.ipynb
- src/langchain_google_cloud_sql_pg/__init__.py
- src/langchain_google_cloud_sql_pg/chat_message_history.py
- src/langchain_google_cloud_sql_pg/engine.py
- src/langchain_google_cloud_sql_pg/postgresql_loader.py
- src/langchain_google_cloud_sql_pg/vectorstore.py
- tests/test_cloudsql_vectorstore.py
- tests/test_cloudsql_vectorstore_from_methods.py
- tests/test_cloudsql_vectorstore_index.py
- tests/test_cloudsql_vectorstore_search.py
- tests/test_postgresql_chatmessagehistory.py
- tests/test_postgresql_engine.py
- tests/test_postgresql_loader.py
> chore: rename integrations

- samples/langchain_quick_start.ipynb
> doc: fixing colab

- samples/langchain_quick_start.ipynb
> docs: add check for database

- .github/workflows/lint.yml
- .github/workflows/lint_fallback.yml
> chore(ci): add fallback lint

- docs/chat_message_history.ipynb
- docs/document_loader.ipynb
- docs/vector_store.ipynb
> docs: add github links

- src/langchain_google_cloud_sql_pg/engine.py
> fix: sql statement for non-nullable column

- src/langchain_google_cloud_sql_pg/engine.py
Adding missing docstring for helper method
> chore: add docstring for init_vectorstore_table

- .kokoro/requirements.txt
> chore: update kokoro deps

- docs/vector_store.ipynb
Custom vector store code block in notebook adds to the non-custom vector store.
> chore: update sample in vector_store.ipynb

- README.rst
> fix: Readme.rst rendering

- .trampolinerc
> fix: doc release pipeline

- .github/CODEOWNERS
- .github/sync-repo-settings.yaml
> chore: update code owners

- README.rst
> docs: update readme codeblocks

- DEVELOPER.md
> docs: Fix typo in developer.md

- .github/blunderbuss.yml
- .github/header-checker-lint.yml
Add blunderbuss to auto assign issues and prs
> ci: Add blunderbuss config

- .github/workflows/lint.yml
- samples/index_tuning_sample/README.md
- samples/index_tuning_sample/create_vector_embeddings.py
- samples/index_tuning_sample/index_search.py
- samples/index_tuning_sample/requirements.txt
Add index tuning guide and samples
> doc: Add Index Tuning Sample

- .github/sync-repo-settings.yaml
> chore(ci): fix typo in sync-repo-settings.yaml

- src/langchain_google_cloud_sql_pg/chat_message_history.py
- src/langchain_google_cloud_sql_pg/engine.py
- src/langchain_google_cloud_sql_pg/indexes.py
- src/langchain_google_cloud_sql_pg/loader.py
- src/langchain_google_cloud_sql_pg/vectorstore.py
> docs: Add docstring to all methods

- integration.cloudbuild.yaml
- src/langchain_google_cloud_sql_pg/engine.py
- tests/test_postgresql_engine.py
Allow user to override default IAM credentials
> feat: Support IAM account override

- docs/document_loader.ipynb
- src/langchain_google_cloud_sql_pg/engine.py
[b/353480319](http://b/353480319)
- Added some documentation in `src/engine.py` for errors and parameters
- Hardcoded table name now uses `TABLE_NAME` var set by the user
- Added an example for Document Saver
> docs: added example for document saver

- src/langchain_google_cloud_sql_pg/indexes.py
pgvector reference for vector functions: https://github.com/pgvector/pgvector?tab=readme-ov-file#vector-functions
> fix: Rename inner product distance search function to inner_product

- .coveragerc
- DEVELOPER.md
- src/langchain_google_cloud_sql_pg/loader.py
- src/langchain_google_cloud_sql_pg/vectorstore.py
- tests/test_cloudsql_vectorstore.py
- tests/test_cloudsql_vectorstore_index.py
- tests/test_cloudsql_vectorstore_search.py
- tests/test_postgresql_loader.py
Add tests and delete duplicate function.
Fix some typos in docs where`alloydb` is used instead of `cloud sql`.
> feat: Add tests to reach 90% coverage

- docs/vector_store.ipynb
Fixes [b/343215179](http://b/343215179) 🦕
> docs: added vector store initialization from documents

- src/langchain_google_cloud_sql_pg/engine.py
Fixes a bug where async loop being used could differ from the connector and the rest of the operations the class used. 
Use a consistent background thread/loop between all classes to help address this.
> fix: add caching for background loop/thread

- requirements.txt
fix: Fixed extra char in requirements.txt
> fix: Fixed extra char in requirements.txt

- src/langchain_google_cloud_sql_pg/chat_message_history.py
- src/langchain_google_cloud_sql_pg/engine.py
- src/langchain_google_cloud_sql_pg/loader.py
- src/langchain_google_cloud_sql_pg/vectorstore.py
> feat: Add support for custom schema names

- samples/index_tuning_sample/requirements.txt
- samples/langchain_on_vertexai/prebuilt_langchain_agent_template.py
- samples/langchain_on_vertexai/requirements.txt
- samples/langchain_on_vertexai/retriever_agent_with_history_template.py
- samples/langchain_on_vertexai/retriever_chain_template.py
- samples/requirements.txt
> chore(samples): update langchain on vertexai requirement testing

- pyproject.toml
fix: updating the minimum langchain core version to 0.2.36
> fix: updating the minimum langchain core version to 0.2.36

- integration.cloudbuild.yaml
- src/langchain_google_cloud_sql_pg/async_chat_message_history.py
- src/langchain_google_cloud_sql_pg/async_loader.py
- src/langchain_google_cloud_sql_pg/async_vectorstore.py
- src/langchain_google_cloud_sql_pg/chat_message_history.py
- src/langchain_google_cloud_sql_pg/engine.py
- src/langchain_google_cloud_sql_pg/loader.py
- src/langchain_google_cloud_sql_pg/vectorstore.py
- tests/test_async_chatmessagehistory.py
- tests/test_async_loader.py
- tests/test_async_vectorstore.py
- tests/test_async_vectorstore_from_methods.py
- tests/test_async_vectorstore_index.py
- tests/test_async_vectorstore_search.py
- tests/test_chatmessagehistory.py
- tests/test_engine.py
- tests/test_loader.py
- tests/test_vectorstore.py
- tests/test_vectorstore_from_methods.py
- tests/test_vectorstore_index.py
- tests/test_vectorstore_search.py
BEGIN_COMMIT_OVERRIDE
feat: refactor to support both async and sync usage
fix!: support async and sync versions of indexing methods
feat: add support for sync from_engine
feat: add from_engine_args method
END_COMMIT_OVERRIDE
> feat!: refactor to support both async and sync usage

- samples/langchain_on_vertexai/README.md
> chore: release 0.10.0

- DEVELOPER.md
> chore(docs): Update DEVELOPER.md

- .kokoro/release.sh
- .kokoro/release/common.cfg
> chore(ci): fix kokoro release secret

- samples/index_tuning_sample/create_vector_embeddings.py
- samples/index_tuning_sample/index_search.py
- samples/langchain_on_vertexai/clean_up.py
- samples/langchain_on_vertexai/create_embeddings.py
- samples/langchain_on_vertexai/requirements.txt
> chore(samples): update samples for async/sync refactor

- .kokoro/release.sh
- .kokoro/release/common.cfg
chore(ci): update kokoro secret
> chore(ci): update kokoro secret

- README.rst
> docs: add benefits to readme

- samples/README.md
docs: Adding a readme to itemise sample notebooks.
> docs: Adding a readme to itemise sample notebooks.

- src/langchain_google_cloud_sql_pg/async_vectorstore.py
fix: query and return only selected metadata columns
> fix: query and return only selected metadata columns

- .github/header-checker-lint.yml
- .github/workflows/docs.yml
chore: update gh workflow permissions
> chore: update gh workflow permissions

- src/langchain_google_cloud_sql_pg/async_vectorstore.py
chore: Convert id field in document to str
This PR is raised as, due to a UI issue this [comment](https://github.com/googleapis/langchain-google-cloud-sql-pg-python/pull/276#discussion_r1978031088) was not resolved before merging the [PR](https://github.com/googleapis/langchain-google-cloud-sql-pg-python/pull/276)
> chore: Convert id field in document to str

- src/langchain_google_cloud_sql_pg/engine.py
Seems required from https://github.com/googleapis/langchain-google-alloydb-pg-python/pull/393
> fix(engine): loop error on close

- README.rst
- docs/langgraph_checkpoint.ipynb
- noxfile.py
- pyproject.toml
- requirements.txt
- src/langchain_google_cloud_sql_pg/__init__.py
- src/langchain_google_cloud_sql_pg/async_checkpoint.py
- src/langchain_google_cloud_sql_pg/checkpoint.py
- src/langchain_google_cloud_sql_pg/engine.py
- tests/test_async_checkpoint.py
- tests/test_checkpoint.py
- tests/test_engine.py
> feat(langgraph): Add Langgraph Checkpointer

- README.rst
> fix(docs): Fix link in README

- src/langchain_google_cloud_sql_pg/async_checkpoint.py
fix: Update JSON conversion
Fixes #294 🦕
> fix: Update JSON conversion method

- .github/renovate.json5
Similar to https://github.com/googleapis/langchain-google-alloydb-pg-python/pull/458
> chore: Update renovate config
